services:
  - type: web
    name: telegram-prediction-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: API_ID
        value: 2917761
      - key: API_HASH
        value: a8639172fa8d35dbfd8ea46286d349ab
      - key: BOT_TOKEN
        value: 8674132351:AAG3ReHocLGtPxkLPl2TOEDtNRn1lea7Dzg
      - key: ADMIN_ID
        value: 6180384006
      - key: SOURCE_CHANNEL_ID
        value: -1002682552255
      - key: PREDICTION_CHANNEL_ID
        value: -1003746077228
      - key: PREDICTION_OFFSET
        value: 2
      - key: TELEGRAM_SESSION
        sync: false
